deleted depcreated files

diff --git a/src/machineconfig/scripts/linux/fire b/src/machineconfig/scripts/linux/fire
--- a/src/machineconfig/scripts/linux/fire
+++ b/src/machineconfig/scripts/linux/fire
@@ -8,12 +8,13 @@ if [ -f "$op_script" ]; then
 fi
 
 
-{
-  chafa "$HOME/code/machineconfig/assets/aafire.webp" --speed 1 --duration 1 --symbols ascii
-} || {
-  echo "An error occurred while executing the script."
-}
-
+if [ "$TERM" = "xterm-256color" ]; then
+  {
+    chafa "$HOME/code/machineconfig/assets/aafire.webp" --speed 1 --duration 1 --symbols ascii
+  } || {
+    echo "An error occurred while executing the script."
+  }
+fi
 # timeout 0.5s aafire  #  -driver slang
 # clear
 
