new release

diff --git a/src/machineconfig/scripts/linux/mount_drive b/src/machineconfig/scripts/linux/mount_drive
--- a/src/machineconfig/scripts/linux/mount_drive
+++ b/src/machineconfig/scripts/linux/mount_drive
@@ -27,6 +27,19 @@ bitlocker_status=$(lsblk -o FSTYPE "/dev/$device" | grep -o BitLocker)
 if [ "$bitlocker_status" = "BitLocker" ];  then
     echo ">>>>>> Drive is bitlocker encrypted, therefore, bitlocker is needded"
     # If drive is bitlocker , following: https://www.linuxuprising.com/2019/04/how-to-mount-bitlocker-encrypted.html
+
+    # check if password is stored here: $HOME/dotfiles/creds/data/bitlocker_pwd if so, read it.
+    # if not, prompt user for password and store it in the file.
+    if [ -f "$HOME/dotfiles/creds/data/bitlocker_pwd" ]; then
+        echo ">>>>>> Bitlocker Password file detected at default location $HOME/dotfiles/creds/data/bitlocker_pwd"
+        bitlocker_pwd=$(cat $HOME/dotfiles/creds/data/bitlocker_pwd)
+    else
+        echo ">>>>>> Password file does not exist"
+        read -p "Enter bitlocker password: " bitlocker_pwd
+        echo $bitlocker_pwd > $HOME/dotfiles/creds/data/bitlocker_pwd
+    fi
+
+
     sudo mkdir -p /media/$mnt_name"_bitlocker"
     sudo dislocker /dev/$device -u -- /media/$mnt_name"_bitlocker" # Will be prompted for password (-u)
     # sudo mount -o loop /media/bitlocker/dislocker-file /media/bitlockermount
@@ -35,6 +48,15 @@ if [ "$bitlocker_status" = "BitLocker" ];  then
 else
     echo "Drive is not encrypted"
     sudo mount --source /dev/$device --target /media/$mnt_name
+fi
+
+# echo a success message if mount was successful (last command) else print error message
+if [ $? -eq 0 ]; then
+    echo "The drive has been successfully mounted at /media/$mnt_name"
+    echo "--------------------------------------"
+else
+    echo "There was an error while mounting the drive. Please check your input and try again."
+    exit 1
 fi
 
 # https://askubuntu.com/questions/1059228/how-to-mount-a-usb-drive-in-ubuntu-18-04
