fix(mount_nfs): comment out error message for unavailable NFS share folder fix(mount_nfs.py): remove custom input option for local mount point selection fix(utils.py): add custom_input parameter to display_options function signature

diff --git a/src/machineconfig/scripts/linux/mount_nfs b/src/machineconfig/scripts/linux/mount_nfs
--- a/src/machineconfig/scripts/linux/mount_nfs
+++ b/src/machineconfig/scripts/linux/mount_nfs
@@ -24,10 +24,11 @@ if ! ping -c 1 "$remote_server" &> /dev/null; then
   echo "Error: Remote server $remote_server is not reachable."
   exit 1
 fi
-if ! showmount -e "$remote_server" | grep -q "$share_path"; then
-  echo "Error: NFS share folder $share_path is not available on $remote_server."
-  exit 1
-fi
+
+#if ! showmount -e "$remote_server" | grep -q "$share_path"; then
+#  echo "Error: NFS share folder $share_path is not available on $remote_server."
+#  exit 1
+#fi
 
 # Check if the share is already mounted
 if mount | grep -q ":$share_path on "; then
